### ISSUE TITLE
Mapa Mental Web 3.0 - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Edwin14459#1]
[Mapa Mental Web 3.0 - Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Edwin14459/files/14514498/Mapa.Mental.Web.3.0.-.Edwin.Lopez.Santiago.pdf)

**Comment by Elisahadad** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
